.job_template: &job_definition
  stage: test
  before_script:
    - apt update
    - apt install -y pdal llvm
  script:
    - pip install .
    - pip install .[dev]
    - pytest
    - flake8 setup.py py3dtiles/ docs/
    # TODO move that in unit tests
    - py3dtiles info tests/pointCloudRGB.pnts
  tags:
    - gitlab-org-docker

# oldest supported
test:python35:
  <<: *job_definition
  image: python:3.5

# latest
test:python-latest:
  <<: *job_definition
  image: python:latest

# stretch
test:python-stretch:
  <<: *job_definition
  image: python:3.7-stretch

#########
# PAGES #
#########
pages:
  stage: deploy
  image: python:latest
  script:
    - pip install .
    - pip install .[doc]
    # sphinx-multiversion needs to have all the branches
    - git remote add upstream https://gitlab.com/Oslandia/py3dtiles.git
    - git fetch upstream
    - sphinx-multiversion docs public
    - cp -rv docs/index_redirect.html public/index.html
    - current_version="$(git tag --list | tail -n1)"
    - sed -i "s/VERSION/$current_version/g" public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
